name: Node.js e estático CI

on:
  pull_request:
  push:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: node-static-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: kleberrangel1983/.github/.github/workflows/node-static-ci.yml@e787db620da12239042187aad34d1cdbf49ad3f4
